### ISSUE TITLE
On the topic of Module dependencies...

### ISSUE THREAD

**Issue by TylerLeonhardt** [Windos/PoshNotify#12]
Sadly, for people to use this module, they'll have to install both MacNotify and PSNotifySend... this is not ideal because you should really only get the modules that are needed for your platform.

I'm not aware of a way to do this inside of the `psd1` (cc @stevel-msft @edyoung) ... allowing something like this would be nice in the module manifest:

```powershell
@{
RequiredModules = if ($IsMacOS) { 'MacNotify' } elseif ($IsLinux) { 'PSNotifySend' } else { @() }
}
```

In the meantime... it's quite possible for us to handle installing the modules within the `psm1`

```powershell
if($IsMacOS -and !(Get-Module MacNotify -list)) {
    Install-Module MacNotify
}

if($IsLinux -and !(Get-Module PSNotifySend -list)) {
    Install-Module PSNotifySend
}
```

but I get scared calling Install-Module ourselves...

**Comment by Windos** [comment]
Also need to consider potential remote uses, e.g. importing module on a
Linux box and invoking in remote Windows (you'd need the module installed
on both in this example but food for thought.)

**Comment by TylerLeonhardt** [comment]
Sad news - MacNotify is taking advantage of PowerShell Core features so the module won't import on Windows PowerShell it seems... take a look at this run... the Windows section:

https://dev.azure.com/TylerLeonhardt/PoshNotify/_build/results?buildId=37

**Comment by TylerLeonhardt** [comment]
We might have a workaround... checking the `PSEdition` in the `psd1`... but still doesn't fully solve the problem.

**Comment by Windos** [comment]
Huh, totally didn't realise you could put logic like that into a psd1 file. Looks like the syntax you listed in your original comment is [supported for root and nested modules](https://docs.microsoft.com/en-us/powershell/gallery/concepts/module-psedition-support#option-2-use-psedition-variable-in-the-psd1-file-to-load-the-proper-dlls-and-nestedrequired-modules).

Worth a try? Would be interested in seeing how it handles install from the gallery with logic in there like that.

**Comment by Windos** [comment]
That PR (#16) is more for discussion than actual merging. In PS Core (Windows) it does try to import the modules... and then complains about not having `bash` >.<

![2018-12-05](https://user-images.githubusercontent.com/6955786/49473355-b4ec1400-f876-11e8-9798-777355623c99.png)

Note, with that change to the psd1 file in place, the module imports perfectly in Windows PowerShell!

**Comment by TylerLeonhardt** [comment]
ah jeez... looks like we can't rely on RequiredModules then 😢

We'll have to go down this route in the psm1... 

```powershell
if($IsMacOS -and !(Get-Module MacNotify -list)) {
    Install-Module MacNotify
}

if($IsLinux -and !(Get-Module PSNotifySend -list)) {
    Install-Module PSNotifySend
}
```

**Comment by TylerLeonhardt** [comment]
I think we've done the best we can with this. Closing for now.
