### ISSUE TITLE
What's left for 0.1.0?

### ISSUE THREAD

**Issue by TylerLeonhardt** [Windos/PoshNotify#22]
should we do #9? Or leave that for 0.2.0?

**Comment by Windos** [comment]
I'd suggest leave #9 and release the MVP.

Should we wire up the release through pipelines?

**Comment by TylerLeonhardt** [comment]
I think that's a great idea 😃

**Comment by Windos** [comment]
Aaaaand we're live.

Just as an FYI, updating the .psd1 file on master will trigger the publish. Something to be aware of when looking at PRs.
