### ISSUE TITLE
Default Icon

### ISSUE THREAD

**Issue by Windos** [Windos/PoshNotify#7]
@TylerLeonhardt, @markwragg, @steviecoaster 

Thoughts on a default icon (for those platforms that support it)?

In the interest of keeping things generic, my vote is for the (/a) PowerShell logo.

**Comment by TylerLeonhardt** [comment]
PowerShell logo makes sense to me.

Another option is the logo but just the outline.

Basically just:

[ >_ ]

No background color.

**Comment by Windos** [comment]
![poshnotify](https://user-images.githubusercontent.com/6955786/49680824-11149980-fafe-11e8-8c36-52b97382e9b1.png)

I've swapped out to the above for a default image. Just based on your suggestion above on PowerShell blue using the Hack font.

Will close this for now, anyone can feel free to ship a better one :P

**Comment by TylerLeonhardt** [comment]
I really like that design!
